kind: ConfigMap
apiVersion: v1
metadata:
  name: dkron-worker
  namespace: {{.Values.namespace}}
data:
  dkron.yml: |-
    kubernetes: true
    retry-join: ["provider=k8s namespace={{.Values.namespace}} label_selector=\"app={{.Values.statefulSetName}}\""]
    # Uncomment below to set a tag for a worker
    tags:
      worker: cron
