apiVersion: v1
kind: Service
metadata:
  name: dkron-server
  labels:
    app: dkron-server
spec:
  publishNotReadyAddresses: true
  ports:
  - name: web
    port: 8080
  - name: rpc
    port: 8946
  - name: raft
    port: 6868
  - name: http-metrics
    port: 9102
  clusterIP: None
  selector:
    app: dkron-server
