kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dkron-server
  namespace: {{.Values.namespace}}
  labels:
    app: dkron-server
subjects:
  - kind: ServiceAccount
    name: dkron
    namespace: {{.Values.namespace}}
roleRef:
  kind: Role
  name: dkron-server
  apiGroup: rbac.authorization.k8s.io
