kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dkron-server
  namespace: {{.Values.namespace}}
  labels:
    app: dkron
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "patch", "get"]
